// Monaco snippet placeholders keep editable fields and the final cursor position.
export const completionSnippets = {
  python: [
    ['def', 'def ${1:name}(${2:args}):\n\t${0:pass}', '함수 정의'],
    ['for', 'for ${1:item} in ${2:items}:\n\t${0:pass}', '반복문'],
    ['class', 'class ${1:Name}:\n\tdef __init__(self, ${2:args}):\n\t\t${0:pass}', '클래스 정의'],
    ['print', 'print(${1:value})$0', '값 출력'],
    ['try', 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:error}:\n\t${0:pass}', '예외 처리'],
  ],
  java: [
    ['main', 'public static void main(String[] args) {\n\t$0\n}', '프로그램 시작점'],
    ['class', 'public class ${1:Name} {\n\t$0\n}', '클래스 정의'],
    ['sout', 'System.out.println(${1:value});$0', '값 출력'],
    ['for', 'for (${1:var} ${2:item} : ${3:items}) {\n\t$0\n}', '컬렉션 반복'],
  ],
  kotlin: [['fun', 'fun ${1:name}(${2:args}): ${3:Unit} {\n\t$0\n}', '함수 정의'], ['for', 'for (${1:item} in ${2:items}) {\n\t$0\n}', '반복문'], ['println', 'println(${1:value})$0', '값 출력']],
  c: [['main', '#include <stdio.h>\n\nint main(void) {\n\t${0}\n\treturn 0;\n}', '프로그램 시작점'], ['for', 'for (int ${1:i} = 0; $1 < ${2:count}; $1++) {\n\t$0\n}', '반복문'], ['printf', 'printf("${1:%d}\\n", ${2:value});$0', '값 출력']],
  cpp: [['main', '#include <iostream>\n\nint main() {\n\t$0\n\treturn 0;\n}', '프로그램 시작점'], ['for', 'for (const auto& ${1:item} : ${2:items}) {\n\t$0\n}', '컬렉션 반복'], ['cout', 'std::cout << ${1:value} << std::endl;$0', '값 출력']],
  csharp: [['class', 'public class ${1:Name}\n{\n\t$0\n}', '클래스 정의'], ['foreach', 'foreach (var ${1:item} in ${2:items})\n{\n\t$0\n}', '반복문'], ['cw', 'Console.WriteLine(${1:value});$0', '값 출력']],
  go: [['main', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t${0:fmt.Println("Hello")}\n}', '프로그램 시작점'], ['func', 'func ${1:name}(${2:args}) ${3:error} {\n\t$0\n}', '함수 정의'], ['for', 'for ${1:index}, ${2:item} := range ${3:items} {\n\t$0\n}', '반복문']],
  rust: [['fn', 'fn ${1:name}(${2:args}) {\n\t$0\n}', '함수 정의'], ['for', 'for ${1:item} in ${2:items} {\n\t$0\n}', '반복문'], ['println', 'println!("{}", ${1:value});$0', '값 출력'], ['match', 'match ${1:value} {\n\t${2:pattern} => ${3:result},\n\t_ => ${0:default},\n}', '패턴 매칭']],
  swift: [['func', 'func ${1:name}(${2:args}) {\n\t$0\n}', '함수 정의'], ['for', 'for ${1:item} in ${2:items} {\n\t$0\n}', '반복문']],
  dart: [['main', 'void main() {\n\t$0\n}', '프로그램 시작점'], ['for', 'for (final ${1:item} in ${2:items}) {\n\t$0\n}', '반복문']],
  ruby: [['def', 'def ${1:name}(${2:args})\n\t$0\nend', '함수 정의'], ['each', '${1:items}.each do |${2:item}|\n\t$0\nend', '컬렉션 반복']],
  php: [['function', 'function ${1:name}(${2:args}) {\n\t$0\n}', '함수 정의'], ['foreach', 'foreach (${1:\\$items} as ${2:\\$item}) {\n\t$0\n}', '반복문']],
  scala: [['def', 'def ${1:name}(${2:args}): ${3:Unit} = {\n\t$0\n}', '함수 정의'], ['for', 'for (${1:item} <- ${2:items}) {\n\t$0\n}', '반복문']],
  lua: [['function', 'local function ${1:name}(${2:args})\n\t$0\nend', '함수 정의'], ['for', 'for ${1:index}, ${2:item} in ipairs(${3:items}) do\n\t$0\nend', '반복문']],
  perl: [['sub', 'sub ${1:name} {\n\t$0\n}', '함수 정의'], ['foreach', 'foreach my ${1:\\$item} (${2:@items}) {\n\t$0\n}', '반복문']],
  elixir: [['defmodule', 'defmodule ${1:Name} do\n\t$0\nend', '모듈 정의'], ['def', 'def ${1:name}(${2:args}) do\n\t$0\nend', '함수 정의']],
  erlang: [['module', '-module(${1:name}).\n-export([${2:main}/0]).\n\n$2() ->\n\t${0:ok}.', '모듈 정의'], ['case', 'case ${1:Value} of\n\t${2:Pattern} -> ${3:Result};\n\t_ -> ${0:Default}\nend', '패턴 매칭']],
  haskell: [['main', 'main :: IO ()\nmain = do\n\t${0:putStrLn "Hello"}', '프로그램 시작점'], ['function', '${1:name} :: ${2:Int} -> ${3:Int}\n$1 ${4:x} = ${0:x}', '함수 정의']],
  ocaml: [['let', 'let ${1:name} ${2:arg} =\n\t$0', '함수 정의'], ['match', 'match ${1:value} with\n| ${2:pattern} -> ${3:result}\n| _ -> ${0:default}', '패턴 매칭']],
  fsharp: [['let', 'let ${1:name} ${2:arg} =\n\t$0', '함수 정의'], ['match', 'match ${1:value} with\n| ${2:pattern} -> ${3:result}\n| _ -> ${0:default}', '패턴 매칭']],
  zig: [['main', 'const std = @import("std");\n\npub fn main() void {\n\t$0\n}', '프로그램 시작점'], ['fn', 'fn ${1:name}(${2:args}) ${3:void} {\n\t$0\n}', '함수 정의']],
  objectivec: [['interface', '@interface ${1:Name} : NSObject\n$0\n@end', '클래스 선언'], ['NSLog', 'NSLog(@"${1:message}");$0', '값 출력']],
  sql: [['select', 'SELECT ${1:*}\nFROM ${2:table}\nWHERE ${0:condition};', '조회'], ['join', 'SELECT ${1:a.*}\nFROM ${2:table_a} AS a\nJOIN ${3:table_b} AS b ON ${0:a.id = b.id};', '테이블 연결'], ['insert', 'INSERT INTO ${1:table} (${2:columns})\nVALUES (${0:values});', '데이터 추가']],
  r: [['function', '${1:name} <- function(${2:args}) {\n\t$0\n}', '함수 정의'], ['for', 'for (${1:item} in ${2:items}) {\n\t$0\n}', '반복문']],
  julia: [['function', 'function ${1:name}(${2:args})\n\t$0\nend', '함수 정의'], ['for', 'for ${1:item} in ${2:items}\n\t$0\nend', '반복문']],
  matlab: [['function', 'function ${1:result} = ${2:name}(${3:args})\n\t$0\nend', '함수 정의'], ['for', 'for ${1:i} = 1:${2:count}\n\t$0\nend', '반복문']],
  bash: [['if', 'if ${1:command}; then\n\t$0\nfi', '조건문'], ['for', 'for ${1:item} in ${2:items}; do\n\t$0\ndone', '반복문'], ['function', '${1:name}() {\n\t$0\n}', '함수 정의']],
  powershell: [['function', 'function ${1:Name} {\n\tparam(${2:args})\n\t$0\n}', '함수 정의'], ['foreach', 'foreach (${1:\\$item} in ${2:\\$items}) {\n\t$0\n}', '반복문']],
  dockerfile: [['from', 'FROM ${1:node:22-alpine}\nWORKDIR /app\nCOPY . .\nRUN ${2:npm ci}\nCMD ["${3:npm}", "${0:start}"]', '이미지 정의']],
  yaml: [['mapping', '${1:key}:\n  ${2:child}: ${0:value}', '중첩 키'], ['list', '${1:items}:\n  - ${0:value}', '목록']],
  toml: [['section', '[${1:section}]\n${2:key} = "${0:value}"', '섹션']],
  graphql: [['query', 'query ${1:Name} {\n\t${2:field} {\n\t\t$0\n\t}\n}', '쿼리'], ['type', 'type ${1:Name} {\n\t${0:id: ID!}\n}', '타입 정의']],
  vue: [['component', '<script setup>\nimport { ref } from "vue";\n${1:const count = ref(0);}\n</script>\n\n<template>\n\t$0\n</template>\n\n<style scoped>\n</style>', 'Vue 컴포넌트']],
  svelte: [['component', '<script>\n\t${1:let message = "Hello";}\n</script>\n\n<p>{message}</p>\n\n<style>\n\t$0\n</style>', 'Svelte 컴포넌트']],
  javascript: [['function', 'function ${1:name}(${2:args}) {\n\t$0\n}', '함수 정의'], ['async', 'async function ${1:name}(${2:args}) {\n\t$0\n}', '비동기 함수']],
  typescript: [['interface', 'interface ${1:Name} {\n\t${0:property: string;}\n}', '인터페이스 정의']],
  html: [['html5', '<!DOCTYPE html>\n<html lang="${1:ko}">\n<head>\n\t<meta charset="UTF-8">\n\t<title>${2:Title}</title>\n</head>\n<body>\n\t$0\n</body>\n</html>', 'HTML 문서']],
  css: [['rule', '${1:.selector} {\n\t${0:display: flex;}\n}', '스타일 규칙']],
  scss: [['mixin', '@mixin ${1:name}(${2:args}) {\n\t$0\n}', '믹스인']],
  json: [['object', '{\n\t"${1:key}": ${0:null}\n}', '객체']],
  xml: [['element', '<${1:element}>\n\t$0\n</$1>', '요소']],
  markdown: [['link', '[${1:텍스트}](${0:https://example.com})', '링크'], ['code', '```${1:language}\n$0\n```', '코드 블록'], ['table', '| ${1:열 1} | ${2:열 2} |\n| --- | --- |\n| ${3:값 1} | ${0:값 2} |', '표']],
};
