import Icon from '../Icon.jsx';

export default function CollaborationSlide({selectSlide}) {
  return (
        <section className="home-slide slide-collab" style={{ gridColumn: 3, gridRow: 2 }} aria-roledescription="슬라이드" aria-label="4 / 5">
          <div className="home-slide-inner page-container"><div className="home-slide-copy"><span className="home-slide-kicker"><i /> ONE CANVAS, MANY MINDS · 04</span><h1>동시에 고쳐도<br /><em>하나의 이야기로.</em></h1><p>메모와 코드 아이디어를 같은 화면에서 함께 다듬고,<br />바뀐 생각은 팀원 화면에 바로 이어집니다.</p><div className="collab-card-row"><article><span>MEMO / LIVE</span><strong>메모를<br />같이 다듬고</strong><small>한 문장도 함께 다듬어요</small></article><article><span>CODE / LIVE</span><strong>코드 생각을<br />이어 붙여요</strong><small>수식도 읽기 좋게 보여요</small></article></div><button className="button button-dark button-large" onClick={() => selectSlide(4)}>다음 장면 <Icon name="arrow" size={18} /></button></div><div className="collab-showcase-stack"><div className="live-edit-showcase"><div className="showcase-window-top"><span><i /><i /><i /></span><strong>idea.js</strong><span className="live-badge"><i /> LIVE</span></div><div className="shared-editor-demo"><div className="editor-lines"><span>01</span><span>02</span><span>03</span><span>04</span></div><code><b>const</b> <em>idea</em> = <strong>"함께 그려요"</strong>;<br />notes.add(<strong>"what if?"</strong>);<br /><b>share</b>(<em>idea</em>, <em>withTeam</em>);<br /><span>지수 · 한 줄 더하는 중</span></code></div><div className="formula-preview"><span>EXPRESSION / 02</span><strong className="formula-display">ƒ(x) = ∑ᵢ xᵢ</strong></div><div className="shared-cursor cursor-minji"><i>M</i> 민지</div></div><div className="text-edit-showcase"><div className="text-edit-showcase-head"><span><Icon name="text" size={13} /><b>공유 메모</b></span><small><i /> MARKDOWN · LIVE</small></div><p>작은 아이디어도 <strong>함께 다듬으면</strong> 더 선명해져요. <span className="remote-caret">민지</span></p></div></div></div>
        </section>
  );
}
